bugapp/urls.py
from django.urls import path
from.import views
from django.contrib import admin
from django.contrib.auth import views as auth_views


app_name = "bugapp"


urlpatterns = [
            path('',views.home,name='home'),    # domain name will be pest here.
            path('admin', views.admin, name="admin"),
            path('contact/', views.contact, name="contact"),
            path('contact/contactsave', views.contactsave, name="contactsave"),
            path('enter2/', views.enter2, name="enter2"),
            path('login/', views.login, name="login"),
            
            path('xx', views.asigned_to, name="asigned_to"),
            path('issue_detail', views.issue_detail, name="issue_detail"),
            path('login/enter2', views.enter2, name="enter2"),
            path('login_page/', views.login_page, name="login_page"),
            path('logout/', auth_views.LogoutView.as_view(template_name='logout.html',
                next_page=None), name="logout"),
            
            #path('notice/', views.notice, name='notice'),
            #path('noticepublish/noticesave', views.noticesave, name='noticesave'),
            path('all_issue/', views.all_issue, name='all_issue'),
            
            path('register/', views.register, name="register"),
            path('register2/register', views.register, name="register2"),
            path('register2/', views.register2, name="register2"),
            path('search/', views.search, name="search"),
            path('userhome/', views.userhome, name="userhome"),
           ]

bugpro/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bugapp.urls')),
]
if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)   

admin.site.index_title ="The Issue Tracker"
admin.site.site_header ="The Issue Tracker Admin"
admin.site.site_title ="Issue Management"

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{{ title }} </title>
        
    </head>
    <body>
      <nav class="navbar fixed-top navbar-expand-lg" style="background-color: #00FFFF;">
      <!--nav class="navbar navbar-expand-lg bg-light"-->
        <!--nav class="navbar navbar-expand dark bg-primary"-->
        <div class="container-fluid">
          <a class="navbar-brand"href="{% url 'skulapp:userhome' %}">User_Home</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
    
          <div class="collapse navbar-collapse" id="navbarSupportedContent"> 
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
             
              <li class="nav-item">
                <a class="nav-link active" href="  ">List</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href=" ">List2</a>
              </li>
              
                <a class="nav-link active"  href=" ">Welcome {{ request.user }}</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href=" ">Logout</a>
              </li>
            </ul>
           
          </div>
        </div>
      </nav>
    <!--body bgcolor=""-->
       
        {% block body_body %}


        {% endblock %}
        
        
        
    </body>
</html>

templates/contact.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
        <!-- JavaScript Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>   
        
        <title>Contact us</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <style>
              #ex1 {
              
              margin-inline: 50px;
            }
            table, th, td {
                border: 1px solid black;
            }
            table.center {
                margin-left: auto;
                margin-right: auto;
            }
            h1{
                text-align: center;
                color:#12225D;
                            }
            h3{
                text-align: center;
                color:red;
                        }
            a{
                text-align: center;
                color:red;
                        }  
            button{
                text-align: center;
                
                        }                      
        </style>
    </head>
    <body>
        <!--------------------Start navbar------------------------>
    <nav class="navbar navbar-expand-lg" style="background-color: #FFA07A;">
        <!--nav class="navbar navbar-expand-lg bg-dark"-->
          <div class="container-fluid">
            <a class="navbar-brand"href="" ></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
           
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            
            </button>
            
            <a class="navbar-brand" href=""> </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </div>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="navbar-brand">
                  <a class="nav-link active" href="{% url 'bugapp:userhome' %}">UserHome</a>
                </li>           
                <li class="navbar-brand">
                  <a class="nav-link active" href="{% url 'bugapp:home' %}">BACK</a>
                </li>
                <li class="navbar-brand">
                  <a class="nav-link active"href="{% url 'bugapp:logout' %}">Logout</a>
                </li>
              </ul>
              </div>
          </div>
        </nav>
        <!--------------------End navbar------------------------>
    <br><h3 >Tell us about the issue.</h3>
      <div id="ex1">
    <form action="contactsave" method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            
              {{ form.as_p }}
              <button type="submit">Upload</button>
          </form>
        </div>
          <div>
            {% for message in messages %}
            <h3>{{message}}</h3>
            {% endfor %}
           </div>
            
       
            
    </body>
</html>

templates/home.html

<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
        <!-- JavaScript Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>   
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Issue</title>
        <link rel="stylesheet" href="">
        <style>
            table, th, td {
              border: 1px solid black;
            }
            table.center {
              margin-left: auto;
              margin-right: auto;
            }
            h1{
                text-align: center;
                color:black;
                          }
            h2{
            text-align: center;
            color:black;
                        }              
            h3{
              text-align: center;
              color:red;
                        }
            h4{
                text-align: center;
                color:red;
                            } 
            h5{
                text-align: center;
                color:black;
                            } 
            p{
                text-align: center;
                color:black;
                style:bold;
                        }                            
            a{
              text-align: center;
              color:red;
                        }  
            nav.sticky.navbar-brand,
            navsticky ul li           
        </style>

    </head>
    <body>
      <!--------------------Start navbar------------------------>
    <!--nav class="navbar fixed-top navbar-light bg-primary"-->
    <nav class="navbar fixed-top navbar-expand-lg" style="background-color: #FFA07A;">
      <!--nav class="navbar navbar-expand-lg" style="background-color: #FFA07A;"-->
      <div class="container-fluid">
        <a class="navbar-brand" href="#"></a>
         <div class="container-fluid">
           
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
           
            </button>
            
                   
            </div>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                
              </ul>
              </div>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="navbar-brand">
                 <a class="nav-link active" href="{% url 'bugapp:contact' %}">Submit</a>
                </li> 
              </ul>
              </div>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="navbar-brand">
                    <a href="{% url 'bugapp:login' %}" class="nav-link active">Log In </a>
                  </li> 
                </ul>
                </div>
                
                     
          </div>
        </nav>
        <!--------------------End navbar------------------------>
        <br><br> <br>



  <h1 class="text-center">Please submit the issue.</h1>
  
 
         
  <br> <br> <br> <br>  <br> <br> <br> <br> <br>  <br>


<!--------------------Footer Start------------------------>
<footer class="bg-success text-white position-relative">
	<p class="text-center">© Copyright 2022-2032 www.Soft Ray.io. All rights reserved. Developed by Soft Ray.</p>
  </footer>
  <!--------------------Footer End------------------------>
  <br>		
</body>
</html>

templates/issue_view.html


{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
 <!-- JavaScript Bundle with Popper -->

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>   
<title>Notice</title>
<style>
    table, th, td {
      width:90 %;
      margin-left:2%;
      border: 1px solid black;
    }
    th {height:50px;}
    td {height:20px;
       width:120px;
    }
    /*table.center {
      margin-left: auto;
      margin-right: auto;
    }*/
    h1{
        text-align: center;
        color:blue;
                  }
    h3{
      text-align: center;
      color:red;
                }
    a{
      text-align: center;
      color:red;
                }            
</style>
</head>
<body> 
   <!--------------------Start navbar------------------------>
   <nav class="navbar navbar-expand-lg" style="background-color: #FFA07A;">
    <!--nav class="navbar navbar-expand-lg bg-dark"-->
      <div class="container-fluid">
        <a class="navbar-brand"href="" ></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
       
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        
        </button>
        
        <a class="navbar-brand" href=""> </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="navbar-brand">
              <a class="nav-link active" href=""></a>
            </li>
            
            <li class="navbar-brand">
              <a class="nav-link active" href="{% url 'bugapp:contact' %}">Contact Us</a>
            </li>
            <li class="navbar-brand">
              <a class="nav-link active"href="{% url 'bugapp:logout' %}">Logout</a>
            </li>
            <li class="navbar-brand">
              <a class="nav-link active" href="{% url 'bugapp:userhome' %}">BACK</a>
            </li>
          </ul>
          </div>
      </div>
    </nav>
    <!--------------------End navbar------------------------>
    <br>
 
  <div>
  <br> 
  <h1 > All issues </h1>
 
        <div>
            <br>
            {% for n in contact %}
            <table class="center" border="4" cellpadding="10"width="800" enctype="multipart/table-data" >
                <tr>
                    <th colspan=10>Issue :- {{n.pk}}</th>
                </tr>
               
              
                <tr>
                  <th colspan=5>Customer name:-{{n.name}} </th><th colspan=5>Customer email:-{{n.email}}</th>
                </tr> 
               
                    <tr>
                      <th colspan=5>Asigned to:-{{n.user.name}} </th><th colspan=5>Role:-{{n.user.role}} </th>
                    </tr>
                    
                    <tr>
                      <th colspan=10>Description:-{{n.desc}} </th>
                    </tr>   
                    <br> 
                 <tr>
                      {% if n.image.url %}
                      <td>
                        <img src="{{n.image.url}}" alt="Uploaded image" width="600px" height-"600px ">
                      </td>
                     
                      {% endif %}  
                        </tr><br> 
                    
                   {% endfor %}
              </table>             
              <br>        
          </div>                         
         
          <br>   <br>   <br>   <br>        
                  
                       
        
         
          
 <!--------------------Footer Start------------------------>
<footer class="bg-success text-white position-relative">
  <p class="text-center">© Copyright 2022-2032 www.Soft Ray.io. All rights reserved. Developed by Soft Ray.</p>
</footer>
<!--------------------Footer End------------------------>
<br>         
</body>
</html>






templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	
	<script type="text/javascript">
		var onloadCallback = function() {
		  grecaptcha.render('html_element', {
			'sitekey' : 'your_site_key'
		  });
		};
	  </script>  

    <title>Login</title>
    <style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: 20px;
			margin-left: 400px;
			margin-bottom: auto;
			/*background: #74cfbf;*/
			background: #7abecc !important;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			/*box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;*/

		}

		.form_container {
			margin-top: 20px;
			margin-left: 20px;
		}

		#form-title{
			color: white;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: black !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
		h1{
			text-align: center;
			color:white;
						}
		h3{
			text-align: center;
			color:red;
						}

		h4{
			text-align: center;
			color:red;
						}
		p{
			text-align: center;
			color:black;
			style:bold;
					}  				


	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h1 id="form-title">LOGIN</h1>
					
				</div>
				
				
				<div class="d-flex justify-content-center form_container">
					
					<form  action="enter2" method="POST">{% csrf_token %}
						
						<div class="input-group mb-3">
							<label for="Enter your user name">Enter your user name:</label>
							<div class="input-group-append">
								
								<input type="text" name="username" placeholder="Enter your name" class="form-control">
							</div><br>
							</div>
							
						<div class="input-group mb-2">
							<label for="Write Password">Write Password:</label>
							<div class="input-group-append">
								<input type="password" name="password" placeholder="Write password" class="form-control">
							</div>
													
						</div>
						
						<br>
				   		<div class="d-flex justify-content-center mt-3 login_container">
								
							<table style="border: 3px solid black">
								<tr>
								<td>Type the number.</td>
								<td>
								<canvas id="myCanvas" width="125" height="60" style="background-color: beige;">{{img}}</canvas>
								
								</td>
								</tr>
								<tr>
								<td><input type="text" class=" placeholder="Enter the number" mt-3 mb-3" name="captha" ></td>
								</tr>
								</table>

						<br/>
						<input class="btn login_btn" type="submit" value="submit">
				   		</div>
						   <div>
							{% for message in messages %}
						    <h3>{{message}}</h3>
							{% endfor %}
						  </div>
					</form>
									</div>
					<div class="mt-4">
						<div class="d-flex justify-content-center links">
							<P>By signin in, you agree to ourTerms and Conditions and Privacy Policy</p> 
					</div>
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						<P>BACK TO HOME PAGE ?</p> <a href="{% url 'bugapp:home' %}" class="ml-2">Home</a>
				</div>
					
				</div>
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
					<p>	Don't have an account? </p><a href="{% url 'bugapp:register2' %}" class="ml-2">Sign Up</a>
				</div>
			</div>
		</div>
	</div>


<br>

<!--------------------Footer Start------------------------>
<footer class="bg-success text-white position-relative">
	<p class="text-center">© Copyright 2022-2032 www.Soft Ray.io. All rights reserved. Developed by Soft Ray.</p>
  </footer>
  <!--------------------Footer End------------------------>
 	
  <script>
	var canvas = document.getElementById("myCanvas");
	var ctx = canvas.getContext("2d");
	ctx.font = "30px Comic Sans MS";
	ctx.fillStyle = "red";
	ctx.textAlign = "center";
	ctx.fillText("{{img}}", canvas.width/2, canvas.height/2);
	</script>
</body>
</html>

templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
	


    <title>Logout</title>
    <style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: 50px;
			margin-left: 400px;
			margin-bottom: auto;
			/*background: #74cfbf;*/
			*background: #7abecc !important;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			/*box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;*/

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: black;
		}
		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
        h1{
            text-align: center;
            color:blue;
                      }
		h3{
		text-align: center;
		color:blue;
					}
	
		h4{
			text-align: center;
			color:red;
						}							  
       
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h1 id="form-title">Bug Tracker and Issue Management program</h1>
				</div>
				<div class="d-flex justify-content-center form_container">

									<div class="mt-4">
					<div class="d-flex justify-content-center links">
                        <h1>Logout successful.</h1>
						<h3>Want to log in again?</h3> <a href="{% url 'bugapp:login' %}" class="ml-2"><h4>Login</h4></a>
					</div>
					<div class="mt-4">
						<div class="d-flex justify-content-center links">
							<h3>BACK TO HOME PAGE ?</h3> <a href="{% url 'bugapp:home' %}" class="ml-2"><h4>Home</h4></a>
					</div>
				</div>
			</div>
		</div>
	
	</div>
	<br><br><br><br><br><br><br><br><br><br>
<!--------------------Footer Start------------------------>

<footer class="bg-success text-white position-relative">
	
	<h4 class="text-center">© Copyright 2022-2032 www.Soft Ray.io. All rights reserved. Developed by Soft Ray.</h4>
    
</footer>


  <!--------------------Footer End------------------------>
  <br>
</body>
</html>

templates/navbar.html
<!DOCTYPE html>

<html>
    <head>
        <title>Navbar</title>
        
    </head>
    <body>
        <!--------------------Start navbar------------------------>
    <nav class="navbar navbar-expand-lg" style="background-color: #ff0000;font-color: #fff;">
        <!--nav class="navbar navbar-expand-lg bg-dark"-->
          <div class="container-fluid">
            <a class="navbar-brand"href="" ></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
                    
            
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                
                  <li class="navbar-brand">
                    {% if request.user.is_staff %}
                   
                    <a class="nav-link active" href="{% url 'bugapp:all_issue' %}">Issue_list</a>
                    {% endif %}
                  </li>
                  <li class="navbar-brand">
                    <a class="nav-link active" href="{% url 'bugapp:home' %}">Home</a>
                  </li>
                  <li class="navbar-brand">
                    <a class="nav-link active" href="{% url 'bugapp:contact' %}">Submit</a>
                  </li>
                  
                  <li class="navbar-brand">
                    <a class="nav-link active"id= "Hello-msg" >Welcome       {{request.user}}</a>
                  </li>

                 
                  <li class="navbar-brand">
                    <a class="nav-link active"href="{% url 'bugapp:login' %}">Login</a>
                  </li>

                  <li class="navbar-brand">
                    <a class="nav-link active"href="{% url 'bugapp:logout' %}">Logout</a>
                  </li>
                <li class="navbar-brand">
                 <span> </span> 
                </li>
              </ul>
              </div>
          </div>
        </nav>
        <!--------------------End navbar------------------------>
        
        <script src="" async defer></script>
    </body>
</html>

templates/userhome.html
{% extends 'main.html' %}

{% load static %}
{% block content %}

<title>{{ title}}</title>



    <style>
      #Hello-msg{
        fontsize:18px;
        color:#FFFFFF;
        margin-left:20px;
      }
      #carddenger{
        
        color:#FFFFFF;
        
        }
      #card{
        fontsize:18px;
        display: flex;  
        margin-top:20px;
        margin-left:20px;
        }
        table, th, td {
          border: 1px solid black;
        }
        table.center {
          margin-left: auto;
          margin-right: auto;
        }
        h1{
            text-align: center;
            color:#12225D;
                      }
        h3{
          text-align: center;
          color:red;
                    }
        a{
          text-align: center;
          color:red;
                    }  
        button{
          text-align: center;
          
                    }                      
    </style>

    
    
   
 
  
  
  <h1 >Hello {{ request.user }} welcome to your dashboard.</h1><br>
  {% if request.user.is_staff %}
           
            <div class="container text-center">
                <div class="row row-cols-4"> 
                   
           
                <div class="card text-bg-primary mb-3"id="card" style="max-width: 15rem;">
                    
                  <div class="card-header">Issue_list</div>
                    <div class="card-body">
                       <!--h5 class="card-title">Primary card title</h5-->
                      <h5> <a href="{% url 'bugapp:all_issue' %}"class="card-title">Click here</a></h5>
                      <p class="card-text">For quick entry the information of client/s.</p>
                  </div>
                </div>
                
                     
                   
              
              
               
              <div class="card text-bg-danger mb-3"id="card" style="max-width: 15rem;">
                <div class="card-header">Admin dashboard </div>
                  <div class="card-body">
                    <h5> <a href="{% url 'bugapp:admin' %}"class="card-title">Click here</a></h5>
                    
                    <p class="card-text">Admin panel login</p>
                  </div>
               </div>
            </div>
        </div>
        {% endif %}
    <br>
    
    
         
    


<br><br><br><br><br><br><br><br><br><br><br><br><br>    
{% endblock %}      